using Avalonia;
using Avalonia.Controls;
using Avalonia.Controls.Primitives;
using Avalonia.Data;
using Avalonia.Layout;
using Avalonia.Media;
using Avalonia.Media.Imaging;
using Avalonia.Platform.Storage;
using Avalonia.Threading;
using LexPercent.Core;
using LexPercent.Domain;
using LexPercent.Documents;
using LexPercent.Storage;
using System.Globalization;
using System.Diagnostics;
namespace LexPercent.UI;

public sealed partial class MainWindow : Window
{
    readonly ProjectStore store = new(); readonly Calculator calculator = new();
    ProjectFile file = new(); AppSettings settings = SettingsStore.Load(); string? path;
    bool dirty, busy, loading, closeAllowed; string page = "Общие сведения";
    readonly Dictionary<string, TextBox> fields = []; CheckBox? fixedRate;
    readonly ContentControl body = new(); readonly TextBlock status = new(); readonly TextBlock subtitle = new(); readonly StackPanel recent = new() { Spacing = 5 };
    readonly TextBox search = new() { PlaceholderText = "Номер, фамилия, дата", Margin = new(0, 0, 0, 12) };
    readonly DispatcherTimer autosave = new();
    static readonly IBrush Navy = Brush.Parse("#132D3F"), Teal = Brush.Parse("#147D79"), Muted = Brush.Parse("#607484");
    public MainWindow()
    {
        Title = "LexPercent Pro"; Width = 1280; Height = 860; MinWidth = 960; MinHeight = 640; Background = Brush.Parse("#F3F5F6"); FontFamily = "Segoe UI";
        var shell = new Grid { ColumnDefinitions = new("245,*"), RowDefinitions = new("*,32") };
        var side = new StackPanel { Margin = new(20), Spacing = 9 }; side.Children.Add(new TextBlock { Text = "LEXPERCENT", FontSize = 24, FontWeight = FontWeight.Bold, Foreground = Brushes.White }); side.Children.Add(new TextBlock { Text = "ПРОЦЕНТЫ · ДОКУМЕНТЫ", FontSize = 10, Foreground = Brush.Parse("#98BCC9"), Margin = new(0, 0, 0, 24) });
        foreach (var name in new[] { "Общие сведения", "Ключевая ставка ЦБ", "История ставок ЦБ РФ", "События", "Результат", "Документ", "История" }) { var nav = Button(name, () => Navigate(name)); nav.HorizontalAlignment = HorizontalAlignment.Stretch; nav.HorizontalContentAlignment = HorizontalAlignment.Left; nav.Background = Brush.Parse("#234253"); nav.Foreground = Brushes.White; side.Children.Add(nav); }
        side.Children.Add(new Separator { Margin = new(0, 15) }); side.Children.Add(new TextBlock { Text = "ПРОЕКТЫ", Foreground = Brushes.White, FontWeight = FontWeight.Bold }); side.Children.Add(search); side.Children.Add(recent); search.TextChanged += async (_, _) => await RefreshRecent();
        shell.Children.Add(new Border { Background = Navy, Child = new ScrollViewer { Content = side } });
        var main = new Grid { RowDefinitions = new("Auto,Auto,*"), Margin = new(26, 18) }; Grid.SetColumn(main, 1); shell.Children.Add(main);
        var heading = new StackPanel { Spacing = 4 }; heading.Children.Add(new TextBlock { Text = "Расчёт процентов", FontSize = 27, FontWeight = FontWeight.SemiBold, Foreground = Navy }); heading.Children.Add(subtitle); subtitle.Foreground = Muted; main.Children.Add(heading);
        var toolbar = new WrapPanel { Orientation = Orientation.Horizontal, Margin = new(0, 16, 0, 18) };
        toolbar.Children.Add(Button("Новый", NewProject)); toolbar.Children.Add(Button("Открыть", Open)); toolbar.Children.Add(Button("Сохранить", () => Save(false))); toolbar.Children.Add(Button("Сохранить как", () => Save(true))); toolbar.Children.Add(Button("Копировать", Copy)); toolbar.Children.Add(Button("Эталон", LoadExample)); toolbar.Children.Add(Button("Настройки", () => Settings(false))); toolbar.Children.Add(Button("Справка", Help)); Grid.SetRow(toolbar, 1); main.Children.Add(toolbar);
        Grid.SetRow(body, 2); main.Children.Add(body); var bottom = new Border { Background = Brushes.White, Child = status, Padding = new(12, 5) }; Grid.SetRow(bottom, 1); Grid.SetColumnSpan(bottom, 2); shell.Children.Add(bottom); Content = shell;
        autosave.Interval = TimeSpan.FromMinutes(Math.Max(1, settings.AutosaveMinutes)); autosave.Tick += async (_, _) => { if (dirty && !busy) { try { Commit(); await store.SaveAsync(SettingsStore.RecoveryPath, file, true); status.Text = "Черновик сохранён · " + DateTime.Now.ToString("HH:mm"); } catch (Exception ex) { status.Text = "Автосохранение: " + ex.Message; } } }; autosave.Start();
        Closing += async (_, e) => { if (closeAllowed) return; e.Cancel = true; if (await CanLeave()) { closeAllowed = true; Close(); } };
        Opened += async (_, _) =>
        {
            if (App.Arguments.Contains("--smoke")) { await Smoke(App.Arguments.Last()); closeAllowed = true; Close(); return; }
            if (!settings.Initialized) await Run(() => Settings(true));
            if (File.Exists(SettingsStore.RecoveryPath) && await Ask("Восстановление", "Найден автоматически сохранённый черновик. Открыть его?", "Открыть", "Пропустить") == "Открыть") await Run(async () => { file = await store.LoadAsync(SettingsStore.RecoveryPath); path = null; dirty = true; Render(); });
            StartRateUpdates();
            await RefreshRecent();
        };
        file = new() { Project = Blank() }; Render();
    }
    CalculationProject Blank() => new() { Start = DateOnly.FromDateTime(DateTime.Today), End = DateOnly.FromDateTime(DateTime.Today), ScheduleEnd = DateOnly.FromDateTime(DateTime.Today), FirstAmount = 0, MonthlyAmount = 0, Organization = settings.Organization, Manager = settings.Manager, Signatories = settings.Signatories.Where(s => s.Id == Signatory.Moroz.Id).ToList(), Document = settings.Document };
    Button Button(string label, Func<Task> action) { var b = new Button { Content = label, Padding = new(14, 9), Margin = new(0, 0, 7, 5), CornerRadius = new(6) }; b.Click += async (_, _) => await Run(action); return b; }
    async Task Run(Func<Task> action) { if (busy) return; busy = true; body.IsEnabled = false; try { await action(); } catch (Exception ex) { status.Text = "Не выполнено: " + ex.Message; await Ask("Проверьте данные", ex.Message, "Понятно"); } finally { busy = false; body.IsEnabled = true; } }
    async Task<string> Ask(string title, string message, params string[] choices)
    {
        var dialog = new Window { Title = title, Width = 560, SizeToContent = SizeToContent.Height, MaxHeight = 650, WindowStartupLocation = WindowStartupLocation.CenterOwner, CanResize = false }; var panel = new StackPanel { Margin = new(24), Spacing = 18 }; panel.Children.Add(new ScrollViewer { MaxHeight = 430, Content = new TextBlock { Text = message, TextWrapping = TextWrapping.Wrap } }); var buttons = new WrapPanel(); foreach (var c in choices) { var b = new Button { Content = c, Margin = new(0, 0, 8, 0) }; b.Click += (_, _) => dialog.Close(c); buttons.Children.Add(b); }
        panel.Children.Add(buttons); dialog.Content = panel; return await dialog.ShowDialog<string>(this) ?? choices.Last();
    }
    async Task<bool> CanLeave() { if (!dirty) return true; var answer = await Ask("Несохранённые изменения", "Сохранить изменения текущего проекта?", "Сохранить", "Не сохранять", "Отмена"); if (answer == "Отмена") return false; if (answer == "Сохранить") { try { await Save(false); } catch (Exception ex) { await Ask("Сохранение", ex.Message, "Понятно"); return false; } return !dirty; } return true; }
    void Changed() { if (loading) return; dirty = true; file = file with { Result = null }; status.Text = "Есть изменения · требуется пересчёт"; }
    TextBox Field(string key, string label, string value, Panel parent, double width = 240, bool multi = false)
    {
        var box = new TextBox { Text = value, Width = width, AcceptsReturn = multi, MinHeight = multi ? 70 : 34, TextWrapping = multi ? TextWrapping.Wrap : TextWrapping.NoWrap }; fields[key] = box; var group = new StackPanel { Spacing = 5, Margin = new(0, 0, 18, 14) }; group.Children.Add(new TextBlock { Text = label, Foreground = Muted, FontSize = 12 }); group.Children.Add(box); parent.Children.Add(group); box.TextChanged += (_, _) => { if (box.IsFocused) Changed(); }; return box;
    }
    static DateOnly Date(string s) => DateOnly.TryParseExact(s.Trim(), ["dd.MM.yyyy", "d.M.yyyy", "yyyy-MM-dd"], CultureInfo.InvariantCulture, DateTimeStyles.None, out var d) ? d : throw new ArgumentException("Введите дату в формате ДД.ММ.ГГГГ.");
    static decimal Amount(string s) => decimal.TryParse(s.Replace(" ", "").Replace("\u00a0", "").Replace(',', '.'), NumberStyles.AllowLeadingSign | NumberStyles.AllowDecimalPoint, CultureInfo.InvariantCulture, out var v) ? v : throw new ArgumentException("Введите число, например 6038,45.");
    static int Day(string text) { var n = Amount(text); if (n != decimal.Truncate(n) || n < 1 || n > 31) throw new ArgumentException("Число месяца — целое число от 1 до 31."); return (int)n; }
    void Commit() { if (fields.Count == 0) return; string T(string k) => fields[k].Text ?? ""; file = file with { Project = file.Project with { Number = T("number"), Debtor = T("debtor"), Organization = T("organization"), Manager = T("manager"), Executor = T("executor"), Basis = T("basis"), CalculationDate = Date(T("date")), Start = Date(T("start")), End = Date(T("end")), ScheduleEnd = Date(T("scheduleEnd")), MonthlyDay = Day(T("day")), JanuaryDay = Day(T("january")), FirstAmount = Amount(T("first")), MonthlyAmount = Amount(T("monthly")), FixedRate = fixedRate?.IsChecked == true, FixedRatePercent = fixedRate?.IsChecked == true ? Amount(T("rate")) : file.Project.FixedRatePercent } }; }
    async Task Calculate() { Commit(); UseAvailableCbrRates(); var snapshot = file.Project; var result = await Task.Run(() => calculator.Calculate(snapshot)); file = file with { Result = result }; status.Text = $"Расчёт выполнен · {result.Intervals.Length} интервалов · {result.Days} дней"; }
    async Task Navigate(string target) { Commit(); if (target is "Результат" or "Документ" && file.Result == null) await Calculate(); page = target; Render(); }
    void Render() { loading = true; fields.Clear(); fixedRate = null; subtitle.Text = $"{(string.IsNullOrWhiteSpace(file.Project.Debtor) ? "Новый проект" : file.Project.Debtor)}  /  № {file.Project.Number}  /  {page}"; body.Content = page switch { "Ключевая ставка ЦБ" => RatesView(), "История ставок ЦБ РФ" => CbrHistoryView(), "События" => EventsView(), "Результат" => ResultView(), "Документ" => DocumentView(), "История" => HistoryView(), _ => GeneralView() }; loading = false; }
    Control GeneralView()
    {
        var p = file.Project; var stack = new StackPanel { Spacing = 10 }; stack.Children.Add(TitleBlock("Карточка проекта", "Исходные данные и параметры начислений")); var form = new WrapPanel(); stack.Children.Add(form);
        Field("number", "Номер расчёта", p.Number, form, 130); Field("date", "Дата расчёта", $"{p.CalculationDate:dd.MM.yyyy}", form, 160); Field("debtor", "Фамилия, имя, отчество", p.Debtor, form, 420); Field("organization", "Организация", p.Organization, form, 340); Field("manager", "Руководитель", p.Manager, form, 340); Field("basis", "Основание расчёта", p.Basis, form, 710, true); Field("executor", "Произвольная подпись (если подписанты ниже не выбраны)", p.Executor, form, 710, true);
        stack.Children.Add(SignatorySelection());
        Field("start", "Первое начисление", $"{p.Start:dd.MM.yyyy}", form, 170); Field("scheduleEnd", "Последнее начисление", $"{p.ScheduleEnd:dd.MM.yyyy}", form, 170); Field("end", "Расчёт по дату включительно", $"{p.End:dd.MM.yyyy}", form, 210); Field("first", "Первоначальная сумма, руб.", p.FirstAmount.ToString(CultureInfo.InvariantCulture), form, 210); Field("monthly", "Следующие начисления, руб.", p.MonthlyAmount.ToString(CultureInfo.InvariantCulture), form, 210); Field("day", "Число месяца", p.MonthlyDay.ToString(), form, 130); Field("january", "Число в январе", p.JanuaryDay.ToString(), form, 130);
        stack.Children.Add(TitleBlock("Процентная ставка", "Выберите режим и задайте применяемые проценты."));
        fixedRate = new CheckBox { Content = "Фиксированная ставка на весь период (иначе — ключевая ставка ЦБ России)", IsChecked = p.FixedRate, Margin = new(0, 0, 10, 12) };
        stack.Children.Add(fixedRate);
        var rates = new WrapPanel { IsVisible = p.FixedRate };
        Field("rate", "Фиксированная ставка, % годовых", p.FixedRatePercent.ToString(CultureInfo.InvariantCulture), rates, 260); stack.Children.Add(rates);
        var keyRates = new StackPanel { IsVisible = !p.FixedRate, Spacing = 6 };
        keyRates.Children.Add(new TextBlock { Text = $"Ключевая ставка ЦБ России: внесено {p.Events.Count(e => e.Kind == EventKind.Rate)} значений. Укажите ставку на начало расчёта и все её изменения.", TextWrapping = TextWrapping.Wrap, Foreground = Muted });
        keyRates.Children.Add(Button("Ввести ключевую ставку ЦБ России", () => Navigate("Ключевая ставка ЦБ"))); stack.Children.Add(keyRates);
        fixedRate.IsCheckedChanged += (_, _) => { rates.IsVisible = fixedRate.IsChecked == true; keyRates.IsVisible = !rates.IsVisible; Changed(); };
        var actions = new WrapPanel(); actions.Children.Add(Button("Сформировать график", async () => { Commit(); if (file.Project.Events.Any(e => e.Automatic) && await Ask("График начислений", "Пересоздать автоматические начисления? Изменённые вручную записи сохранятся.", "Пересоздать", "Отмена") != "Пересоздать") return; file = file with { Project = Calculator.GenerateSchedule(file.Project), Result = null }; dirty = true; await Navigate("События"); })); actions.Children.Add(Button("Рассчитать", () => Navigate("Результат"))); stack.Children.Add(actions); return Scroll(stack);
    }
    static Control Scroll(Control c) => new ScrollViewer { Content = c, HorizontalScrollBarVisibility = ScrollBarVisibility.Disabled };
    static Control TitleBlock(string title, string caption) => new StackPanel { Spacing = 5, Margin = new(0, 0, 0, 15), Children = { new TextBlock { Text = title, FontSize = 20, FontWeight = FontWeight.SemiBold, Foreground = Navy }, new TextBlock { Text = caption, Foreground = Muted, TextWrapping = TextWrapping.Wrap } } };
    static DataGrid GridFor<T>(IEnumerable<T> items, params (string Header, string Path, double Width)[] columns) { var grid = new DataGrid { ItemsSource = items, AutoGenerateColumns = false, IsReadOnly = true, GridLinesVisibility = DataGridGridLinesVisibility.Horizontal, SelectionMode = DataGridSelectionMode.Single, MinHeight = 190, Background = Brushes.White, RowHeight = 36 }; foreach (var c in columns) grid.Columns.Add(new DataGridTextColumn { Header = c.Header, Binding = new Binding(c.Path), Width = new DataGridLength(c.Width, DataGridLengthUnitType.Star) }); return grid; }
    Control EventsView()
    {
        var grid = GridFor(file.Project.Events.OrderBy(e => e.Date).ThenBy(e => e.Kind).ToArray(), ("Дата", "DateText", 1), ("Событие", "KindText", 1.2), ("Сумма / ставка", "ValueText", 1.2), ("Комментарий", "Comment", 2), ("Источник", "OriginText", 1)); var layout = new Grid { RowDefinitions = new("Auto,Auto,*,Auto") }; layout.Children.Add(TitleBlock("События расчёта", "Начисления, оплаты и ставки в одном списке. Выберите строку для изменения."));
        var filterRow = new WrapPanel(); var filter = new ComboBox { ItemsSource = new[] { "Все события", "Начисления", "Оплаты", "Ставки" }, SelectedIndex = 0, Width = 170, Margin = new(0, 0, 12, 12) };
        var filterText = new TextBox { PlaceholderText = "Поиск по дате, сумме, комментарию", Width = 360 }; filterRow.Children.Add(filter); filterRow.Children.Add(filterText); Grid.SetRow(filterRow, 1); layout.Children.Add(filterRow);
        void Filter() { var q = filterText.Text ?? ""; grid.ItemsSource = file.Project.Events.Where(e => (filter.SelectedIndex == 0 || e.Kind == (filter.SelectedIndex == 1 ? EventKind.Accrual : filter.SelectedIndex == 2 ? EventKind.Payment : EventKind.Rate)) && ($"{e.DateText} {e.ValueText} {e.Comment}".Contains(q, StringComparison.OrdinalIgnoreCase))).OrderBy(e => e.Date).ThenBy(e => e.Kind).ToArray(); }
        filter.SelectionChanged += (_, _) => Filter(); filterText.TextChanged += (_, _) => Filter(); Grid.SetRow(grid, 2); layout.Children.Add(grid);
        var edit = new StackPanel { Spacing = 8, Margin = new(0, 15, 0, 0) }; var row = new WrapPanel(); var dateBox = new TextBox { Text = $"{file.Project.Start:dd.MM.yyyy}", Width = 150, Margin = new(0, 0, 10, 0) }; var kind = new ComboBox { ItemsSource = new[] { "Начисление", "Оплата", "Ставка" }, SelectedIndex = 0, Width = 160, Margin = new(0, 0, 10, 0) }; var value = new TextBox { PlaceholderText = "Сумма / %", Width = 150, Margin = new(0, 0, 10, 0) }; var comment = new TextBox { PlaceholderText = "Комментарий", Width = 250 }; foreach (var c in new Control[] { dateBox, kind, value, comment }) row.Children.Add(c); edit.Children.Add(row);
        Guid? selected = null; grid.SelectionChanged += (_, _) => { if (grid.SelectedItem is CalculationEvent e) { selected = e.Id; dateBox.Text = e.DateText; kind.SelectedIndex = e.Kind == EventKind.Accrual ? 0 : e.Kind == EventKind.Payment ? 1 : 2; value.Text = e.ValueText; comment.Text = e.Comment; } };
        Task Put(bool update) { var k = kind.SelectedIndex == 0 ? EventKind.Accrual : kind.SelectedIndex == 1 ? EventKind.Payment : EventKind.Rate; if (update && selected == null) throw new ArgumentException("Выберите событие в таблице."); var e = new CalculationEvent(update ? selected!.Value : Guid.NewGuid(), Date(dateBox.Text ?? ""), k, Amount(value.Text ?? ""), comment.Text ?? ""); var list = file.Project.Events.Where(x => !update || x.Id != e.Id).Append(e).ToList(); var p = file.Project with { Events = list }; Calculator.Validate(p); file = file with { Project = p, Result = null }; dirty = true; Render(); return Task.CompletedTask; }
        var actions = new WrapPanel(); actions.Children.Add(Button("Добавить", () => Put(false))); actions.Children.Add(Button("Сохранить изменение", () => Put(true))); actions.Children.Add(Button("Удалить", async () => { if (selected == null) return; if (await Ask("Удаление события", "Удалить выбранное событие?", "Удалить", "Отмена") != "Удалить") return; file = file with { Project = file.Project with { Events = file.Project.Events.Where(e => e.Id != selected).ToList() }, Result = null }; dirty = true; Render(); })); actions.Children.Add(Button("Рассчитать", () => Navigate("Результат"))); edit.Children.Add(actions); Grid.SetRow(edit, 3); layout.Children.Add(edit); return layout;
    }
    Control ResultView()
    {
        if (file.Result is not { } r) return TitleBlock("Расчёт не выполнен", "Заполните исходные данные и нажмите «Рассчитать»."); var layout = new Grid { RowDefinitions = new("Auto,Auto,*,Auto") }; layout.Children.Add(TitleBlock("Результат расчёта", $"{file.Project.Start:dd.MM.yyyy} — {file.Project.End:dd.MM.yyyy} · округление каждого интервала")); var cards = new WrapPanel(); void Card(string name, string value) { cards.Children.Add(new Border { Background = Brushes.White, CornerRadius = new(8), Padding = new(18), Margin = new(0, 0, 14, 16), MinWidth = 170, Child = new StackPanel { Spacing = 8, Children = { new TextBlock { Text = name, Foreground = Muted, FontSize = 12 }, new TextBlock { Text = value, FontSize = 23, Foreground = Teal, FontWeight = FontWeight.SemiBold } } } }); }
        Card("ПРОЦЕНТЫ", r.Interest.ToString("N2") + " ₽"); Card("ОСНОВНОЙ ДОЛГ", r.Principal.ToString("N2") + " ₽"); Card("ДНИ / ИНТЕРВАЛЫ", $"{r.Days} / {r.Intervals.Length}"); if (r.Advance > 0) Card("ПЕРЕПЛАТА", r.Advance.ToString("N2") + " ₽"); Grid.SetRow(cards, 1); layout.Children.Add(cards); var grid = GridFor(r.Intervals, ("Период", "Period", 2), ("Долг, руб.", "DebtText", 1.2), ("Ставка", "RateText", 1), ("Дней", "Days", .7), ("Проценты, руб.", "InterestText", 1.2)); Grid.SetRow(grid, 2); layout.Children.Add(grid); var actions = new WrapPanel { Margin = new(0, 14, 0, 0) }; actions.Children.Add(Button("Справка и экспорт", () => Navigate("Документ"))); actions.Children.Add(Button("Протокол расчёта", async () => { await Ask("Протокол расчёта", Report.Create(file.Project, r, true).PlainText(), "Закрыть"); })); Grid.SetRow(actions, 3); layout.Children.Add(actions); return layout;
    }
    Control DocumentView()
    {
        var panel = new Grid { RowDefinitions = new("Auto,Auto,Auto,*") };
        panel.Children.Add(TitleBlock("Справка и протокол", "Страницы ниже соответствуют экспортируемому PDF."));
        var protocol = new CheckBox { Content = "Подробный протокол вместо справки" }; Grid.SetRow(protocol, 1); panel.Children.Add(protocol);
        var actions = new WrapPanel(); foreach (var ext in new[] { "pdf", "docx", "xlsx" }) actions.Children.Add(Button("Экспорт " + ext.ToUpperInvariant(), () => Export(ext, protocol.IsChecked == true)));
        actions.Children.Add(Button("Печать / открыть PDF", async () => { if (file.Result == null) await Calculate(); var preview = Path.Combine(SettingsStore.DirectoryPath, "preview.pdf"); Directory.CreateDirectory(SettingsStore.DirectoryPath); Exporter.Export(preview, Report.Create(file.Project, file.Result!, protocol.IsChecked == true)); Process.Start(new ProcessStartInfo(preview) { UseShellExecute = true }); }));
        actions.Children.Add(Button("Оформление", Formatting)); Grid.SetRow(actions, 2); panel.Children.Add(actions);
        var pages = new StackPanel { Spacing = 18 }; var scroll = Scroll(pages); Grid.SetRow(scroll, 3); panel.Children.Add(scroll);
        void Refresh() { pages.Children.Clear(); pages.Children.Add(new PdfPreview(Report.Create(file.Project, file.Result!, protocol.IsChecked == true))); }
        protocol.IsCheckedChanged += (_, _) => Refresh(); Refresh(); return panel;
    }
    Control HistoryView()
    {
        var panel = new Grid { RowDefinitions = new("Auto,*,Auto") }; panel.Children.Add(TitleBlock("История версий", "Сохранение без изменений не создаёт версию. Восстановление сохраняет предыдущую историю.")); var grid = GridFor(file.Versions.OrderByDescending(v => v.Number).ToArray(), ("Версия", "Number", .5), ("Дата и время", "SavedAt", 1.4), ("Изменения", "Description", 3)); Grid.SetRow(grid, 1); panel.Children.Add(grid); var buttons = new WrapPanel { Margin = new(0, 12, 0, 0) }; buttons.Children.Add(Button("Просмотреть", async () => { if (grid.SelectedItem is ProjectVersion v) await Ask($"Версия {v.Number}", v.Result == null ? v.Description : Report.Create(v.Project, v.Result).PlainText(), "Закрыть"); })); buttons.Children.Add(Button("Восстановить", async () => { if (grid.SelectedItem is not ProjectVersion v) return; if (await Ask("Восстановить версию", $"Сделать версию {v.Number} текущей?", "Восстановить", "Отмена") != "Восстановить") return; file = store.Restore(file, v.Number); dirty = true; Render(); })); buttons.Children.Add(Button("Сравнить с текущей", async () => { if (grid.SelectedItem is ProjectVersion v) await Ask($"Сравнение с версией {v.Number}", ProjectStore.Compare(v.Project, file.Project) + $"\nПроценты: {v.Result?.Interest:N2} → {file.Result?.Interest:N2}", "Закрыть"); })); buttons.Children.Add(Button("Сравнить две версии", CompareVersions)); Grid.SetRow(buttons, 2); panel.Children.Add(buttons); return panel;
    }
    async Task NewProject() { if (!await CanLeave()) return; file = new() { Project = Blank() }; path = null; dirty = false; page = "Общие сведения"; Render(); }
    async Task LoadExample() { if (!await CanLeave()) return; fields.Clear(); file = new() { Project = ReferenceExample.Create() }; path = null; dirty = true; page = "Результат"; await Calculate(); Render(); }
    async Task Open() { if (!await CanLeave()) return; var picks = await StorageProvider.OpenFilePickerAsync(new() { Title = "Открыть проект", AllowMultiple = false, FileTypeFilter = [new("Проект LexPercent") { Patterns = ["*.lpp", "*.bak"] }] }); if (picks.Count > 0) await OpenPath(picks[0].TryGetLocalPath()!); }
    async Task OpenPath(string selected) { var loaded = await store.LoadAsync(selected); Calculator.Validate(loaded.Project); loaded = loaded with { Result = await Task.Run(() => calculator.Calculate(loaded.Project)) }; file = loaded; path = selected; dirty = false; page = "Результат"; Render(); Remember(selected); }
    async Task Save(bool asNew) { Commit(); if (file.Result == null) await Calculate(); var target = path; if (asNew || target == null) { var pick = await StorageProvider.SaveFilePickerAsync(new() { Title = "Сохранить проект", SuggestedStartLocation = Directory.Exists(settings.ProjectDirectory) ? await StorageProvider.TryGetFolderFromPathAsync(settings.ProjectDirectory) : null, SuggestedFileName = $"{file.Project.Number} — {file.Project.Debtor}.lpp", DefaultExtension = "lpp", FileTypeChoices = [new("Проект LexPercent") { Patterns = ["*.lpp"] }] }); target = pick?.TryGetLocalPath(); if (target == null) return; } file = await store.SaveAsync(target, file); path = target; dirty = false; Remember(target); if (File.Exists(SettingsStore.RecoveryPath)) File.Delete(SettingsStore.RecoveryPath); status.Text = "Сохранено · " + Path.GetFileName(path); if (page == "История") Render(); }
    async Task Copy() { Commit(); if (!await CanLeave()) return; var answer = await Ask("Копирование", "Очистить оплаты в новом проекте?", "Очистить оплаты", "Сохранить оплаты", "Отмена"); if (answer == "Отмена") return; file = ProjectStore.Copy(file, answer == "Очистить оплаты"); path = null; dirty = true; page = "Общие сведения"; Render(); }
    async Task Export(string ext, bool protocol) { Commit(); if (file.Result == null) await Calculate(); var pick = await StorageProvider.SaveFilePickerAsync(new() { Title = "Экспорт документа", SuggestedFileName = $"{file.Project.Debtor} — {(protocol ? "Протокол" : "Справка")}.{ext}", DefaultExtension = ext, FileTypeChoices = [new(ext.ToUpperInvariant()) { Patterns = ["*." + ext] }] }); if (pick?.TryGetLocalPath() is { } target) { var report = Report.Create(file.Project, file.Result!, protocol); await Task.Run(() => Exporter.Export(target, report)); status.Text = "Документ сохранён: " + target; } }
    void Remember(string p) { settings = settings with { Recent = settings.Recent.Where(x => x != p).Prepend(p).Take(50).ToList() }; SettingsStore.Save(settings); _ = RefreshRecent(); }
    async Task RefreshRecent() { var query = search.Text ?? ""; var paths = settings.Recent.Where(File.Exists).ToList(); try { if (Directory.Exists(settings.ProjectDirectory)) paths.AddRange(Directory.EnumerateFiles(settings.ProjectDirectory, "*.lpp")); } catch (IOException) { } catch (UnauthorizedAccessException) { } var matches = new List<(string Path, string Label)>(); foreach (var p in paths.Distinct().Take(200)) { try { var f = await store.LoadAsync(p); string label = $"№ {f.Project.Number} — {f.Project.Debtor}\n{f.Project.CalculationDate:dd.MM.yyyy} · {File.GetLastWriteTime(p):dd.MM.yyyy}"; if (label.Contains(query, StringComparison.OrdinalIgnoreCase)) matches.Add((p, label)); } catch { } } if (query != (search.Text ?? "")) return; recent.Children.Clear(); foreach (var e in matches.Take(15)) { var b = Button(e.Label, async () => { if (await CanLeave()) await OpenPath(e.Path); }); b.FontSize = 11; b.Foreground = Brushes.White; b.Background = Brush.Parse("#234253"); b.HorizontalAlignment = HorizontalAlignment.Stretch; b.Content = new TextBlock { Text = e.Label, TextWrapping = TextWrapping.Wrap }; recent.Children.Add(b); } }
}
